---
name: gfm-demo site
markdown: kramdown
baseurl: "/gfm-demo"

collections:
  doc-troubleshooting:
    output: true
#    permalink: /troubleshooting/:path/
  doc-interfaces:
    output: true
#    permalink: /troubleshooting/:path/